// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ4-zNJBAXy_cVS1Z-p3A1NIR1He5sLoc',
    appId: '1:331985474803:web:93ad0886737b3c668ad386',
    messagingSenderId: '331985474803',
    projectId: 'grand-storeapp',
    authDomain: 'grand-storeapp.firebaseapp.com',
    storageBucket: 'grand-storeapp.appspot.com',
    measurementId: 'G-RWQ1H66H24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzau3_H6_SDge-igoBRqcTLsBgRtoEAJ4',
    appId: '1:331985474803:android:9e69b58db19a5edb8ad386',
    messagingSenderId: '331985474803',
    projectId: 'grand-storeapp',
    storageBucket: 'grand-storeapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GIeeXEUC9DPhTxnZD_eN0Tga0MG4Ghs',
    appId: '1:331985474803:ios:7d77883ea60e9d7d8ad386',
    messagingSenderId: '331985474803',
    projectId: 'grand-storeapp',
    storageBucket: 'grand-storeapp.appspot.com',
    iosBundleId: 'com.example.grandStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5GIeeXEUC9DPhTxnZD_eN0Tga0MG4Ghs',
    appId: '1:331985474803:ios:0f7a39f1e5bda1588ad386',
    messagingSenderId: '331985474803',
    projectId: 'grand-storeapp',
    storageBucket: 'grand-storeapp.appspot.com',
    iosBundleId: 'com.example.grandStoreApp.RunnerTests',
  );
}
